### ISSUE TITLE
SqlMigration fails when using sql files that end with a newline

### ISSUE THREAD

**Issue by altrive** [gitbucket/solidbase#11]
### Issue
SqlMigration fails when following conditions met.

- Using latest version 1.01 (which may not be officially released)
- DB migration target is MySQL (It's not occurred when using DB2/PostgreSQL)
- SQL files that end with a newline.

### Exception message
> com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Query was empty

### Notes
I've confirmed this issue by GitBucket dev build.
Following SQL files fails to migrate.
- gitbucket-core_4.0.sql
- gitbucket-core_4.7.sql

**Comment by takezoe** [comment]
Fixed in 0f51efb3af646ebcb5add1922d889b09becf4f07
