### ISSUE TITLE
Create release 1.0.3

### ISSUE THREAD

**Issue by aadrian** [gitbucket/solidbase#16]
Please create and publish a new release - v1.0.3
in order to be able to use it across the projects that depend on this.

Thank you.

**Comment by takezoe** [comment]
@aadrian Just curious, is there any new feature what you need? or do you need dependency updates?

**Comment by aadrian** [comment]
@takezoe only dependency updates so that libraries can work with JDK 11 and OpenJDKs.

**Comment by takezoe** [comment]
@aadrian I see. I will release 1.0.3 as soon as possible.

**Comment by aadrian** [comment]
@takezoe Isn't there any simple way to automate the release and publish process?

I mean not only for this project but for most projects since it seems quite tedious?, e.g. by just setting a tag in Git and let scripts do the rest?

AFAIK Grails Framework seems to take this approach.

**Comment by takezoe** [comment]
In solidbase, release process isn't much troublesome for now. It's done in about 3 minutes if sonatype is fine. It's very easier than GitBucket's release process. The most time consuming task in release process of GitBucket is writing a blog post but it's impossible to be automated.

Anyway, 1.0.3 has been released.

**Comment by aadrian** [comment]
@takezoe thank you.

> It's done in about 3 minutes if sonatype is fine.

With Sonatype it also involves necessary manual steps and logging in.
AFAIK JFrog Artifactory would not require that, only an initial setup.


> Anyway, solidbase 1.0.3 has been released.

Thank you very much.
