### ISSUE TITLE
missing solidbase in maven central

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/solidbase#7]
with [PR-13](https://github.com/gitbucket-plugins/gitbucket-h2-backup-plugin/pull/13) in gitbucket-h2-backup-plugin, a dependency to solidbase has been introduced but the artifact cannot be found in central.

**Comment by takezoe** [comment]
Oops, sorry. I will publish as soon as possible.

**Comment by takezoe** [comment]
Published.

**Comment by McFoggy** [comment]
no pb I also adapted the builds to query multiple repositories

**Comment by takezoe** [comment]
Synched to the Maven central repository just now:
https://repo1.maven.org/maven2/io/github/gitbucket/solidbase/1.0.0/
